# Development docker-compose file

version: '3.3'

services:
  app:
    build:
      context: .
      args:
        env: ${ENVIRONMENT:-development}
    image: gcr.io/${PROJECT-local}/${IMAGE:-app}:${TAG:-dev}
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    ports:
      - 20080:80
    environment:
      PHP_ENABLE_XDEBUG: 1

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: dev_db
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_pwd
    ports:
      - 3306:3306
